CCDNForum\ForumBundle\Entity\Category:
    type: entity
    table: CC_Forum_Category
    repositoryClass: CCDNForum\ForumBundle\Repository\CategoryRepository
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
        listOrderPriority:
            type: integer
            column: list_order_priority
    oneToMany:
        boards:
            targetEntity: CCDNForum\ForumBundle\Entity\Board
            mappedBy: category
            cascade: ["persist"]
