parameters:

    # Service Parameters defined in app/config
    ccdn_forum_forum.model.utility.pagination_config.class: CCDNForum\ForumBundle\Model\Utility\PaginationConfig
    ccdn_forum_forum.model.utility_bag.class: CCDNForum\ForumBundle\Model\Utility\Bag\UtilityBag

services:

    #
    # Gateways.
    #
    ccdn_forum_forum.gateway_bag:
        class: %ccdn_forum_forum.gateway_bag.class%
        arguments: [@service_container]

    ccdn_forum_forum.gateway.category:
        class: %ccdn_forum_forum.gateway.category.class%
        arguments:
            - @doctrine
            - @knp_paginator
            - @ccdn_forum_forum.gateway_bag
            - %ccdn_forum_forum.entity.category.class%

    ccdn_forum_forum.gateway.board:
        class: %ccdn_forum_forum.gateway.board.class%
        arguments:
            - @doctrine
            - @knp_paginator
            - @ccdn_forum_forum.gateway_bag
            - %ccdn_forum_forum.entity.board.class%

    ccdn_forum_forum.gateway.topic:
        class: %ccdn_forum_forum.gateway.topic.class%
        arguments:
            - @doctrine
            - @knp_paginator
            - @ccdn_forum_forum.gateway_bag
            - %ccdn_forum_forum.entity.topic.class%

    ccdn_forum_forum.gateway.post:
        class: %ccdn_forum_forum.gateway.post.class%
        arguments:
            - @doctrine
            - @knp_paginator
            - @ccdn_forum_forum.gateway_bag
            - %ccdn_forum_forum.entity.post.class%

    ccdn_forum_forum.gateway.draft:
        class: %ccdn_forum_forum.gateway.draft.class%
        arguments:
            - @doctrine
            - @knp_paginator
            - @ccdn_forum_forum.gateway_bag
            - %ccdn_forum_forum.entity.draft.class%

    ccdn_forum_forum.gateway.registry:
        class: %ccdn_forum_forum.gateway.registry.class%
        arguments:
            - @doctrine
            - @knp_paginator
            - @ccdn_forum_forum.gateway_bag
            - %ccdn_forum_forum.entity.registry.class%

    ccdn_forum_forum.gateway.subscription:
        class: %ccdn_forum_forum.gateway.subscription.class%
        arguments:
            - @doctrine
            - @knp_paginator
            - @ccdn_forum_forum.gateway_bag
            - %ccdn_forum_forum.entity.subscription.class%

    #
    # Repositories.
    #
    ccdn_forum_forum.repository.category:
        class: %ccdn_forum_forum.repository.category.class%
        arguments:
            - @doctrine
            - @security.context
            - @ccdn_forum_forum.gateway.category
            - @ccdn_forum_forum.model.utility_bag

    ccdn_forum_forum.repository.board:
        class: %ccdn_forum_forum.repository.board.class%
        arguments:
            - @doctrine
            - @security.context
            - @ccdn_forum_forum.gateway.board
            - @ccdn_forum_forum.model.utility_bag

    ccdn_forum_forum.repository.topic:
        class: %ccdn_forum_forum.repository.topic.class%
        arguments:
            - @doctrine
            - @security.context
            - @ccdn_forum_forum.gateway.topic
            - @ccdn_forum_forum.model.utility_bag

    ccdn_forum_forum.repository.post:
        class: %ccdn_forum_forum.repository.post.class%
        arguments:
            - @doctrine
            - @security.context
            - @ccdn_forum_forum.gateway.post
            - @ccdn_forum_forum.model.utility_bag

    ccdn_forum_forum.repository.draft:
        class: %ccdn_forum_forum.repository.draft.class%
        arguments:
            - @doctrine
            - @security.context
            - @ccdn_forum_forum.gateway.draft
            - @ccdn_forum_forum.model.utility_bag

    ccdn_forum_forum.repository.registry:
        class: %ccdn_forum_forum.repository.registry.class%
        arguments:
            - @doctrine
            - @security.context
            - @ccdn_forum_forum.gateway.registry
            - @ccdn_forum_forum.model.utility_bag

    ccdn_forum_forum.repository.subscription:
        class: %ccdn_forum_forum.repository.subscription.class%
        arguments:
            - @doctrine
            - @security.context
            - @ccdn_forum_forum.gateway.subscription
            - @ccdn_forum_forum.model.utility_bag

    #
    # Managers.
    #
    ccdn_forum_forum.manager_bag:
        class: %ccdn_forum_forum.manager_bag.class%
        arguments: [@service_container]

    ccdn_forum_forum.manager.category:
        class: %ccdn_forum_forum.manager.category.class%
        arguments:
            - @doctrine
            - @security.context
            - @ccdn_forum_forum.gateway.category
            - @ccdn_forum_forum.manager_bag
            - @ccdn_forum_forum.model.utility_bag

    ccdn_forum_forum.manager.board:
        class: %ccdn_forum_forum.manager.board.class%
        arguments:
            - @doctrine
            - @security.context
            - @ccdn_forum_forum.gateway.board
            - @ccdn_forum_forum.manager_bag
            - @ccdn_forum_forum.model.utility_bag

    ccdn_forum_forum.manager.topic:
        class: %ccdn_forum_forum.manager.topic.class%
        arguments:
            - @doctrine
            - @security.context
            - @ccdn_forum_forum.gateway.topic
            - @ccdn_forum_forum.manager_bag
            - @ccdn_forum_forum.model.utility_bag

    ccdn_forum_forum.manager.post:
        class: %ccdn_forum_forum.manager.post.class%
        arguments:
            - @doctrine
            - @security.context
            - @ccdn_forum_forum.gateway.post
            - @ccdn_forum_forum.manager_bag
            - @ccdn_forum_forum.model.utility_bag

    ccdn_forum_forum.manager.registry:
        class: %ccdn_forum_forum.manager.registry.class%
        arguments:
            - @doctrine
            - @security.context
            - @ccdn_forum_forum.gateway.registry
            - @ccdn_forum_forum.manager_bag
            - @ccdn_forum_forum.model.utility_bag

    ccdn_forum_forum.manager.draft:
        class: %ccdn_forum_forum.manager.draft.class%
        arguments:
            - @doctrine
            - @security.context
            - @ccdn_forum_forum.gateway.draft
            - @ccdn_forum_forum.manager_bag
            - @ccdn_forum_forum.model.utility_bag

    ccdn_forum_forum.manager.subscription:
        class: %ccdn_forum_forum.manager.subscription.class%
        arguments:
            - @doctrine
            - @security.context
            - @ccdn_forum_forum.gateway.subscription
            - @ccdn_forum_forum.manager_bag
            - @ccdn_forum_forum.model.utility_bag

    #
    # Models.
    #
    ccdn_forum_forum.model_bag:
        class: %ccdn_forum_forum.model_bag.class%
        arguments: [@service_container]

    ccdn_forum_forum.model.category:
        class: %ccdn_forum_forum.model.category.class%
        arguments:
            - @ccdn_forum_forum.repository.category
            - @ccdn_forum_forum.manager.category
            - @ccdn_forum_forum.model_bag
            - @ccdn_forum_forum.model.utility_bag

    ccdn_forum_forum.model.board:
        class: %ccdn_forum_forum.model.board.class%
        arguments:
            - @ccdn_forum_forum.repository.board
            - @ccdn_forum_forum.manager.board
            - @ccdn_forum_forum.model_bag
            - @ccdn_forum_forum.model.utility_bag

    ccdn_forum_forum.model.topic:
        class: %ccdn_forum_forum.model.topic.class%
        arguments:
            - @ccdn_forum_forum.repository.topic
            - @ccdn_forum_forum.manager.topic
            - @ccdn_forum_forum.model_bag
            - @ccdn_forum_forum.model.utility_bag

    ccdn_forum_forum.model.post:
        class: %ccdn_forum_forum.model.post.class%
        arguments:
            - @ccdn_forum_forum.repository.post
            - @ccdn_forum_forum.manager.post
            - @ccdn_forum_forum.model_bag
            - @ccdn_forum_forum.model.utility_bag

    ccdn_forum_forum.model.registry:
        class: %ccdn_forum_forum.model.registry.class%
        arguments:
            - @ccdn_forum_forum.repository.registry
            - @ccdn_forum_forum.manager.registry
            - @ccdn_forum_forum.model_bag
            - @ccdn_forum_forum.model.utility_bag

    ccdn_forum_forum.model.draft:
        class: %ccdn_forum_forum.model.draft.class%
        arguments:
            - @ccdn_forum_forum.repository.draft
            - @ccdn_forum_forum.manager.draft
            - @ccdn_forum_forum.model_bag
            - @ccdn_forum_forum.model.utility_bag

    ccdn_forum_forum.model.subscription:
        class: %ccdn_forum_forum.model.subscription.class%
        arguments:
            - @ccdn_forum_forum.repository.subscription
            - @ccdn_forum_forum.manager.subscription
            - @ccdn_forum_forum.model_bag
            - @ccdn_forum_forum.model.utility_bag

    #
    # Model Utilities.
    #
    ccdn_forum_forum.model.utility_bag:
        class: %ccdn_forum_forum.model.utility_bag.class%
        arguments:
            - @ccdn_forum_forum.model.utility.pagination_config
            - @ccdn_forum_forum.model.utility.policy

    ccdn_forum_forum.model.utility.pagination_config:
        class: %ccdn_forum_forum.model.utility.pagination_config.class%
        arguments:
            - %ccdn_forum_forum.subscription.list.topics_per_page%
            - %ccdn_forum_forum.board.show.topics_per_page%
            - %ccdn_forum_forum.topic.show.posts_per_page%
            - %ccdn_forum_forum.draft.list.drafts_per_page%

    ccdn_forum_forum.model.utility.policy:
        class: %ccdn_forum_forum.manager.policy.class%
        arguments:
            - @security.context
            - @ccdn_forum_forum.manager_bag

    ccdn_forum_forum.manager.policy:
        class: %ccdn_forum_forum.manager.policy.class%
        arguments:
            - @security.context
            - @ccdn_forum_forum.manager_bag

    #
    # Post Forms.
    #
    ccdn_forum_forum.form.type.post_create:
        class: %ccdn_forum_forum.form.type.post_create.class%
        arguments:
            - %ccdn_forum_forum.entity.post.class%

    ccdn_forum_forum.form.handler.post_create:
        class: %ccdn_forum_forum.form.handler.post_create.class%
        arguments:
            - @form.factory
            - @ccdn_forum_forum.form.type.post_create
            - @ccdn_forum_forum.manager.post

    ccdn_forum_forum.form.type.post_update:
        class: %ccdn_forum_forum.form.type.post_update.class%
        arguments:
            - %ccdn_forum_forum.entity.post.class%

    ccdn_forum_forum.form.handler.post_update:
        class: %ccdn_forum_forum.form.handler.post_update.class%
        arguments:
            - @form.factory
            - @ccdn_forum_forum.form.type.post_update
            - @ccdn_forum_forum.manager.post

    #
    # Topic Forms.
    #
    ccdn_forum_forum.form.type.topic_create:
        class: %ccdn_forum_forum.form.type.topic_create.class%
        arguments:
            - %ccdn_forum_forum.entity.topic.class%

    ccdn_forum_forum.form.handler.topic_create:
        class: %ccdn_forum_forum.form.handler.topic_create.class%
        arguments:
            - @form.factory
            - @ccdn_forum_forum.form.type.topic_create
            - @ccdn_forum_forum.form.type.post_create
            - @ccdn_forum_forum.manager.topic
            - @ccdn_forum_forum.manager.board

    ccdn_forum_forum.form.type.topic_update:
        class: %ccdn_forum_forum.form.type.topic_update.class%
        arguments:
            - %ccdn_forum_forum.entity.topic.class%

    ccdn_forum_forum.form.handler.topic_update:
        class: %ccdn_forum_forum.form.handler.topic_update.class%
        arguments:
            - @form.factory
            - @ccdn_forum_forum.form.type.topic_update
            - @ccdn_forum_forum.form.type.post_update
            - @ccdn_forum_forum.manager.topic
            - @ccdn_forum_forum.manager.post

    ccdn_forum_forum.form.type.change_topics_board:
        class: %ccdn_forum_forum.form.type.change_topics_board.class%
        arguments:
            - %ccdn_forum_forum.entity.topic.class%

    ccdn_forum_forum.form.handler.change_topics_board:
        class: %ccdn_forum_forum.form.handler.change_topics_board.class%
        arguments:
            - @form.factory
            - @ccdn_forum_forum.form.type.change_topics_board
            - @ccdn_forum_forum.manager.topic
            - @ccdn_forum_forum.manager.board

    #
    # Twig Extensions.
    #
    ccdn_forum_forum.component.twig_extension.board_list:
        class: %ccdn_forum_forum.component.twig_extension.board_list.class%
        arguments:
            - @ccdn_forum_forum.model.category
        tags:
            - { name: twig.extension }

    #
    # Other.
    #
    ccdn_forum_forum.component.flood_control:
       class: %ccdn_forum_forum.component.flood_control.class%
       arguments:
           - @session
           - %ccdn_forum_forum.topic.flood_control.post_limit%
           - %ccdn_forum_forum.topic.flood_control.block_for_minutes%

    #
    # Dashboard Integrator.
    #
    ccdn_forum_forum.component.dashboard.integrator:
        class: %ccdn_forum_forum.component.dashboard.integrator.class%
        tags:
            - { name: ccdn_component_dashboard.integrator }
