CCDNForum\ForumBundle\Entity\Topic:
    properties:
        board:
            - NotNull: { groups: [topic] }
        title:
            - NotBlank: { groups: [topic] }
            - MinLength: { limit: 10, groups: [topic] }
            - MaxLength: { limit: 255, groups: [topic] }

CCDNForum\ForumBundle\Entity\Post:
    properties:
        body:
            - NotBlank: {  groups: [topic, post] }
            - MinLength: { limit: 15, groups: [topic, post] }
            - MaxLength: { limit: 30000, groups: [topic, post] }
