CCDNForum\ForumBundle\Entity\Topic:
    properties:
        board:
            - NotNull: { groups: [topic] }
        title:
            - Type: { type: string, groups: [topic] }
            - NotBlank: { groups: [topic] }
            - MinLength: { limit: 10, groups: [topic] }
            - MaxLength: { limit: 255, groups: [topic] }
    
CCDNForum\ForumBundle\Entity\Post:
    properties:
        body:
            - Type: { type: string, groups: [topic, post] }
            - NotBlank: {  groups: [topic, post] }
            - MinLength: { limit: 50, groups: [topic, post] }
            - MaxLength: { limit: 10000, groups: [topic, post] }
    
CCDNForum\ForumBundle\Entity\Flag:
    properties:
        reason:
            - NotNull: { groups: [flag] }
        description:
            - Type: { type: string, groups: [flag] }
            - NotBlank: { groups: [flag] }
            - MinLength: { limit: 10, groups: [flag] }
            - MaxLength: { limit: 5000, groups: [flag] }

