%ccdn_forum_forum.entity.topic.class%:
    properties:
        board:
            - NotNull: { groups: [topic_create, topic_update] }
        title:
            - Type: { type: string, groups: [topic_create, topic_update] }
            - NotBlank: { groups: [topic_create, topic_update] }
            - MinLength: { limit: 10, groups: [topic_create, topic_update] }
            - MaxLength: { limit: 255, groups: [topic_create, topic_update] }

%ccdn_forum_forum.entity.post.class%:
    properties:
        body:
            - Type: { type: string, groups: [post_create, post_update] }
            - NotBlank: { groups: [post_create, post_update] }
            - MinLength: { limit: 15, groups: [post_create, post_update] }
            - MaxLength: { limit: 30000, groups: [post_create, post_update] }
