parameters:

    # Service Parameters defined in app/config.
    ccdn_forum_forum.component.role_helper.class: CCDNForum\ForumBundle\Component\Helper\RoleHelper
    ccdn_forum_admin.component.event.admin_flash_notices.class: CCDNForum\ForumBundle\Component\Dispatcher\Listener\AdminFlashListener
services:

    #
    # Flood Control.
    #
    ccdn_forum_forum.component.flood_control:
       class: %ccdn_forum_forum.component.flood_control.class%
       arguments:
           - @session
           - %ccdn_forum_forum.topic.flood_control.post_limit%
           - %ccdn_forum_forum.topic.flood_control.block_for_minutes%

    #
    # Dashboard Integrator.
    #
    ccdn_forum_forum.component.dashboard.integrator:
        class: %ccdn_forum_forum.component.dashboard.integrator.class%
        tags:
            - { name: ccdn_component_dashboard.integrator }

    ccdn_forum_forum.component.role_helper:
        class: %ccdn_forum_forum.component.role_helper.class%
        arguments:
            - @security.context
            - %security.role_hierarchy.roles%

    #
    # Event Subscribers.
    #
    ccdn_forum_admin.component.event.admin_flash_notices:
        class: %ccdn_forum_admin.component.event.admin_flash_notices.class%
        arguments: [@session]
        tags:
            - { name: kernel.event_subscriber }
