parameters:

    # Service Parameters defined in app/config.

services:

    #
    # Managers.
    #

    #ccdn_forum_forum.manager_bag:
    #    class: %ccdn_forum_forum.manager_bag.class%
    #    arguments: [@service_container]

    ccdn_forum_forum.manager.forum:
        class: %ccdn_forum_forum.manager.forum.class%
        arguments:
            - @doctrine
            - @security.context
            - @ccdn_forum_forum.gateway.forum
            - @ccdn_forum_forum.model_bag
            - @ccdn_forum_forum.model.utility_bag

    ccdn_forum_forum.manager.category:
        class: %ccdn_forum_forum.manager.category.class%
        arguments:
            - @doctrine
            - @security.context
            - @ccdn_forum_forum.gateway.category
            - @ccdn_forum_forum.model_bag
            - @ccdn_forum_forum.model.utility_bag

    ccdn_forum_forum.manager.board:
        class: %ccdn_forum_forum.manager.board.class%
        arguments:
            - @doctrine
            - @security.context
            - @ccdn_forum_forum.gateway.board
            - @ccdn_forum_forum.model_bag
            - @ccdn_forum_forum.model.utility_bag

    ccdn_forum_forum.manager.topic:
        class: %ccdn_forum_forum.manager.topic.class%
        arguments:
            - @doctrine
            - @security.context
            - @ccdn_forum_forum.gateway.topic
            - @ccdn_forum_forum.model_bag
            - @ccdn_forum_forum.model.utility_bag

    ccdn_forum_forum.manager.post:
        class: %ccdn_forum_forum.manager.post.class%
        arguments:
            - @doctrine
            - @security.context
            - @ccdn_forum_forum.gateway.post
            - @ccdn_forum_forum.model_bag
            - @ccdn_forum_forum.model.utility_bag

    ccdn_forum_forum.manager.registry:
        class: %ccdn_forum_forum.manager.registry.class%
        arguments:
            - @doctrine
            - @security.context
            - @ccdn_forum_forum.gateway.registry
            - @ccdn_forum_forum.model_bag
            - @ccdn_forum_forum.model.utility_bag

    ccdn_forum_forum.manager.subscription:
        class: %ccdn_forum_forum.manager.subscription.class%
        arguments:
            - @doctrine
            - @security.context
            - @ccdn_forum_forum.gateway.subscription
            - @ccdn_forum_forum.model_bag
            - @ccdn_forum_forum.model.utility_bag
