language: php

php:
    - 5.3
    - 5.4
    - 5.5

matrix:
    allow_failures:
        - php: 5.5

env:
    - SYMFONY_VERSION="2.1.*" DB=mysql

before_script:
    - composer self-update
    - composer install --dev --prefer-source

notifications:
    email: status@codeconsortium.com
