language: php

php:
#    - hhvm
    - 5.3
    - 5.4

matrix:
    allow_failures:
        - php: 5.3

before_script:
    - echo 'date.timezone = "Europe/London"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
    - curl -s http://getcomposer.org/installer | php
    - php composer.phar --dev install
    - mysql -u ccdnroot -p root
    #- mysql -e 'CREATE DATABASE ccdndev_travis_test'
    #- mysql > grant usage on *.* to ccdndev_travis_test``
    - php ./Tests/Functional/app/console doctrine:database create
    - php ./Tests/Functional/app/console doctrine:schema:create
    - php ./Tests/Functional/app/console doctrine:schema:update --force

script:
    - 'php ./vendor/bin/phpunit -c ./ --testdox'
    - 'php ./vendor/bin/behat'

after_script:
    - mysql -e 'DROP DATABASE ccdndev_travis_test;'

notifications:
    email: status@codeconsortium.com

