language: php

php:
    - 5.3
    - 5.4
    - 5.5

matrix:
    allow_failures:
        - php: 5.5

env:
    - ISOLATED=true

before_script: composer install --dev --prefer-source

notifications:
    email: status@codeconsortium.com
