
ccdn_forum_admin_forum_list:
    pattern: /
    defaults: { _controller: CCDNForumForumBundle:AdminForum:list }

ccdn_forum_admin_forum_create:
    pattern: /create
    defaults: { _controller: CCDNForumForumBundle:AdminForum:create }

ccdn_forum_admin_forum_create_process:
    pattern: /create/process
    defaults: { _controller: CCDNForumForumBundle:AdminForum:createProcess }

ccdn_forum_admin_forum_edit:
    pattern: /edit/{forumId}
    defaults: { _controller: CCDNForumForumBundle:AdminForum:edit }

ccdn_forum_admin_forum_edit_process:
    pattern: /edit/{forumId}/process
    defaults: { _controller: CCDNForumForumBundle:AdminForum:editProcess }

ccdn_forum_admin_forum_delete:
    pattern: /delete/{forumId}
    defaults: { _controller: CCDNForumForumBundle:AdminForum:delete }

ccdn_forum_admin_forum_delete_process:
    pattern: /delete/{forumId}/process
    defaults: { _controller: CCDNForumForumBundle:AdminForum:deleteProcess }
