
ccdn_forum_admin_category_list:
    pattern: /
    defaults: { _controller: CCDNForumForumBundle:CategoryAdmin:, _locale: en }

ccdn_forum_admin_category_create:
    pattern: /create
    defaults: { _controller: CCDNForumForumBundle:CategoryAdmin:, _locale: en }

ccdn_forum_admin_category_create_process:
    pattern: /create/process
    defaults: { _controller: CCDNForumForumBundle:CategoryAdmin:, _locale: en }

ccdn_forum_admin_category_edit:
    pattern: /edit/{categoryId}
    defaults: { _controller: CCDNForumForumBundle:CategoryAdmin:, _locale: en }

ccdn_forum_admin_category_edit_process:
    pattern: /edit/{categoryId}/process
    defaults: { _controller: CCDNForumForumBundle:CategoryAdmin:, _locale: en }

ccdn_forum_admin_category_remove:
    pattern: /remove/{categoryId}
    defaults: { _controller: CCDNForumForumBundle:CategoryAdmin:, _locale: en }

ccdn_forum_admin_category_remove_confirm:
    pattern: /remove/{categoryId}/confirm
    defaults: { _controller: CCDNForumForumBundle:CategoryAdmin:, _locale: en }
