
#ccdn_forum_user_category_index:
#    pattern: /index
#    defaults: { _controller: CCDNForumForumBundle:UserCategory:index, _locale: en, forumName: default }

ccdn_forum_user_category_index:
    pattern: /
    defaults: { _controller: CCDNForumForumBundle:UserCategory:index, _locale: en, forumName: default }

ccdn_forum_user_category_show:
    pattern: /{categoryId}
    defaults: { _controller: CCDNForumForumBundle:UserCategory:show, _locale: en, forumName: default }
