
ccdn_forum_user_draft_list:
    pattern: /
    defaults: { _controller: CCDNForumForumBundle:UserDraft:list, _locale: en }

ccdn_forum_user_draft_show:
    pattern: /{draftId}/show
    defaults: { _controller: CCDNForumForumBundle:UserDraft:show, _locale: en }

ccdn_forum_user_draft_delete:
    pattern: /{draftId}/delete
    defaults: { _controller: CCDNForumForumBundle:UserDraft:delete, _locale: en }

ccdn_forum_user_draft_publish:
    pattern: /{draftId}/publish
    defaults: { _controller: CCDNForumForumBundle:UserDraft:publish, _locale: en }
