
ccdn_forum_user_subscription_list:
    pattern: /
    defaults: { _controller: CCDNForumForumBundle:UserSubscription:show, _locale: en }

ccdn_forum_user_subscription_subscribe:
    pattern: /topic/{topicId}/subscribe
    defaults: { _controller: CCDNForumForumBundle:UserSubscription:subscribe, _locale: en }

ccdn_forum_user_subscription_unsubscribe:
    pattern: /topic/{topicId}/unsubscribe
    defaults: { _controller: CCDNForumForumBundle:UserSubscription:unsubscribe, _locale: en }
